### ISSUE TITLE
Unable to upload/display images

### ISSUE THREAD

**Issue by omltcat** [BaldissaraMatheus/Tasks.md#136]
Within a card, I have tried:
- Click "Image (Ctrl-G)" - "Browse" or drag/paste in a image > I can see image preview now > Click "Add image"
  - Result: card is immediately closed, and nothing is added to the content
- Click "Image (Ctrl-G)" - "Browse" or drag in a image > I can see image preview now > Drag this preview image into content below
  - Result: getting a super long string starting with `data:image`, but not displayed as a image in rich text mode.

The only way I can add image now is by linking from another website. But on the server I can see that image added above are indeed uploaded to config/images. It just can't be displayed, or am I doing things wrong?

**Comment by BaldissaraMatheus** [comment]
Sorry for the delay. Are you running the app through docker? If so, could you please share your container info? (or the command you used to create the container)

**Comment by omltcat** [comment]
Thanks for your reply.  
Yes I am running it through docker. Here is the compose:

```yaml
services:
  tasks.md:
    image: baldissaramatheus/tasks.md
    container_name: tasks.md
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./tmd/tasks:/tasks
      - ./tmd/config:/config
    restart: always
    ports:
      - 9999:8080
```

I can confirm the the upload happens (and succeeds) when user clicks "Add image". But then the card just closes.

I also tried the [demo](https://editor.stackoverflow.design/) provided by Stacks-Editor. When you click "Add image" there, the relevent image syntax is added to the text.
