### ISSUE TITLE
All tasks missing

### ISSUE THREAD

**Issue by imlogang** [BaldissaraMatheus/Tasks.md#90]
It seems that a couple of days ago, Tasks was updated to 2.0 and now all of the sudden all of my tasks are missing but still present in the Docker container. 

I noticed a new file structure from issue #48 and what is now present on the readme. 
https://github.com/BaldissaraMatheus/Tasks.md?tab=readme-ov-file#docker-compose

My docker compose file: 
```
version: "3.3"
services:
  tasks.md:
    container_name: tasks.md
    environment:
      - PUID=1000
      - PGID=1000
      - TITLE=Tasks
    ports:
      - 8080:8080
    volumes:
      - ~/tasks/files:/tasks
      - ~/tasks/config:/config/
    restart: unless-stopped
    image: baldissaramatheus/tasks.md
networks: {}
```

I can see these files still present on my local Machine. 
```
:~/tasks/files$ ls
 Backlog   Blocked   Doing   Done  'Up Next'  'Wont Do'
```
But seem to not be present on the Docker Container itself.
```
/tasks # ls
/tasks #
```

Am I doing something wrong? 
Since the files are still present locally, should I just recreate my tasks under the new 2.x? 

FWIW, I do not see a directory under `~/tasks/config` yet but that might be because I haven't created anything since I saw it had nothing there anymore.
